### ISSUE TITLE
Input prefix for budget/expense amounts

### ISSUE THREAD

**Issue by victoralvelais** [mujahidali88094/React_Budgets_App#2]
- I think it will be helpful to add a '$' prefix in the budget/expense number inputs.
- I'd also like to see the budget label changed to something more descriptive.

Please assign this issue to me if interested.

![image](https://user-images.githubusercontent.com/6127592/195012950-ba907ac3-066b-423d-ab22-569521ed2b5a.png)

**Comment by mujahidali88094** [comment]
assigned you @vcaiii .
